exports.getBlogListModel = () => {
    let res = [
        {
            id:100001,
            title:'如何编写一个ajax？(1)',
            blogType:'original',
            description:'那么我们如何才能编写一个普遍使用的ajax呢？那么我们如何才能编写一个普遍使用的ajax呢？那么我们如何才能编写一个普遍使用的ajax呢？',
            lastUpdatedTime:1502275412000,
            visitor: 262,
            commentCount:0,
            comments:[],
        },
        {
            id:100002,
            title:'如何编写一个ajax？(2)',
            blogType:'reproduced',
            description:'那么我们如何才能编写一个普遍使用的ajax呢？那么我们如何才能编写一个普遍使用的ajax呢？那么我们如何才能编写一个普遍使用的ajax呢？',
            lastUpdatedTime:1502475412000,
            visitor: 22,
            commentCount:0,
            comments:[],
        },
        {
            id:100003,
            title:'如何编写一个ajax？(1)',
            blogType:'original',
            description:'那么我们如何才能编写一个普遍使用的ajax呢？那么我们如何才能编写一个普遍使用的ajax呢？那么我们如何才能编写一个普遍使用的ajax呢？',
            lastUpdatedTime:1502275412000,
            visitor: 262,
            commentCount:0,
            comments:[],
        },
        {
            id:100004,
            title:'如何编写一个ajax？(2)',
            blogType:'reproduced',
            description:'那么我们如何才能编写一个普遍使用的ajax呢？那么我们如何才能编写一个普遍使用的ajax呢？那么我们如何才能编写一个普遍使用的ajax呢？',
            lastUpdatedTime:1502475412000,
            visitor: 22,
            commentCount:0,
            comments:[],
        },
        {
            id:100005,
            title:'如何编写一个ajax？(1)',
            blogType:'original',
            description:'那么我们如何才能编写一个普遍使用的ajax呢？那么我们如何才能编写一个普遍使用的ajax呢？那么我们如何才能编写一个普遍使用的ajax呢？',
            lastUpdatedTime:1502275412000,
            visitor: 262,
            commentCount:0,
            comments:[],
        },
        {
            id:100006,
            title:'如何编写一个ajax？(2)',
            blogType:'reproduced',
            description:'那么我们如何才能编写一个普遍使用的ajax呢？那么我们如何才能编写一个普遍使用的ajax呢？那么我们如何才能编写一个普遍使用的ajax呢？',
            lastUpdatedTime:1502475412000,
            visitor: 22,
            commentCount:0,
            comments:[],
        },
        {
            id:100007,
            title:'如何编写一个ajax？(1)',
            blogType:'original',
            description:'那么我们如何才能编写一个普遍使用的ajax呢？那么我们如何才能编写一个普遍使用的ajax呢？那么我们如何才能编写一个普遍使用的ajax呢？',
            lastUpdatedTime:1502275412000,
            visitor: 262,
            commentCount:0,
            comments:[],
        },
        {
            id:100008,
            title:'如何编写一个ajax？(2)',
            blogType:'reproduced',
            description:'那么我们如何才能编写一个普遍使用的ajax呢？那么我们如何才能编写一个普遍使用的ajax呢？那么我们如何才能编写一个普遍使用的ajax呢？',
            lastUpdatedTime:1502475412000,
            visitor: 22,
            commentCount:0,
            comments:[],
        },
        {
            id:100009,
            title:'如何编写一个ajax？(1)',
            blogType:'original',
            description:'那么我们如何才能编写一个普遍使用的ajax呢？那么我们如何才能编写一个普遍使用的ajax呢？那么我们如何才能编写一个普遍使用的ajax呢？',
            lastUpdatedTime:1502275412000,
            visitor: 262,
            commentCount:0,
            comments:[],
        },
        {
            id:100010 ,
            title:'如何编写一个ajax？(2)',
            blogType:'reproduced',
            description:'那么我们如何才能编写一个普遍使用的ajax呢？那么我们如何才能编写一个普遍使用的ajax呢？那么我们如何才能编写一个普遍使用的ajax呢？',
            lastUpdatedTime:1502475412000,
            visitor: 22,
            commentCount:0,
            comments:[],
        },
    ]
    return res;
},
exports.getBlogDetailModel = () => {
    let res = {
        id:100001,
        title:'如何编写一个ajax？(1)',
        blogType:'original',
        description:'那么我们如何才能编写一个普遍使用的ajax呢？那么我们如何才能编写一个普遍使用的ajax呢？那么我们如何才能编写一个普遍使用的ajax呢？',
        lastUpdatedTime:1502275412000,
        visitor: 262,
        commentCount:0,
        comments:[],
    };
    return res;
}
